# Trabalho 1 - Random walk

## Índice

1. [Primeiro caso de teste](#1.-Primeiro-caso-de-teste)<br>
    1.1. [Random Walk](#Random-Walk)<br>
    1.2. [Otimização](#Otimização)
2. [Segundo caso de teste](#2.-Segundo-caso-de-teste)
3. [Terceiro caso de teste](#3.-Terceiro-caso-de-teste)

## 1. Primeiro caso de teste

In [15]:
import numpy as np

pop = np.random.uniform(low=0 , high=1 , size = (3,3))
pop

array([[0.62610924, 0.03903488, 0.41523571],
       [0.31176402, 0.85177924, 0.74878053],
       [0.49039804, 0.9015492 , 0.90095929]])

In [16]:
def funcao(x):
    x1=x[0]
    x2=x[1]
    x3=x[2]
    return 10 * (x1 - 1)**2 + 20 * (x2 - 2)**2 + 30 * (x3 - 3)**2

In [17]:
#converter valores
lb = [-3,-2,0]
ub = [3,4,6]
x=[]
for i in range(len(lb)):
    x.append(lb[i]+(ub[i]-lb[i])*pop[0:,i:i+1])
x=np.array(x)

In [18]:
result = funcao(x)
result

array([[291.97553973],
       [136.85921073],
       [224.53750964]])

### Random Walk

### Otimização

## 2. Segundo caso de teste

In [19]:
#Palavra alvo
palavraAlvo = np.array([
52.547,
72.154,
53.694,
57.771,
115.88,
105.59,
75.368,
126.02,
52.756,
85.100,
80.525,
111.24,
113.62,
64.95,
89.181,
85.647,
101.71,
106.75,
110.37,
72.082,
104.38,
102.41,
63.009,
59.52,
89.869,
126.78,
77.231,
96.821,
67.905,
110.1])

#Palavra aleatoria
palavra = np.random.uniform(low=palavraAlvo.min(), high=palavraAlvo.max(), size=np.size(palavraAlvo))
palavra = np.round_(palavra, decimals = 3)
palavra

array([ 57.193,  54.756, 108.577, 107.619,  70.677,  70.348,  99.654,
       126.456,  88.198, 115.176, 120.911,  86.306,  95.978, 114.081,
        63.93 ,  87.614, 125.225,  54.751,  84.729,  91.758,  92.219,
       100.282, 105.058,  56.302, 124.788,  53.771,  81.167, 110.181,
       106.925,  76.185])

In [20]:
#função diferença entre as palavras
def pont(p1,p2):
    import math
    diferenca = []

    for i,j in zip(p1,p2):
        diferenca.append((i - j)**2)
        pontuacao = sum(diferenca)
    return pontuacao

In [21]:
pont(palavraAlvo, palavra)

33125.333361000005

## 3. Terceiro caso de teste

In [22]:
#função rastrigin
def rastrigin(x):
    return 10 * len(x) + sum(i * i - 10 * cos(2 * pi * i) for i in x)